schema_version: "0.1.0"
kind: declarative_http_connector
id: shopify
display_name: Shopify
connector_type: SHOPIFY
connector_family: API
description: Declarative Shopify Admin connector for sync-oriented dataset materialization.
base_url: https://example.myshopify.com/admin/api/2025-01
test_connection_path: /shop.json

auth:
  strategy: header_token
  token_field: access_token
  token_label: Access Token
  header_name: X-Shopify-Access-Token
  header_template: "{access_token}"

pagination:
  strategy: cursor
  response_items_field: customers
  limit_param: limit
  cursor_param: page_info
  next_cursor_source: link_header
  link_header_param: page_info
  default_page_size: 100
  max_page_size: 250

incremental:
  strategy: request_param
  request_param: updated_at_min
  cursor_field: updated_at
  cursor_type: iso_datetime

resources:
  # - key: orders
  #   label: Orders
  #   path: /orders.json
  #   primary_key: id
  #   supports_incremental: true
  #   default_sync_mode: INCREMENTAL
  #   response_items_field: orders
  #   request_params:
  #     status: any
  #   description: Shopify order records.

  # - key: customers
  #   label: Customers
  #   path: /customers.json
  #   primary_key: id
  #   supports_incremental: true
  #   default_sync_mode: INCREMENTAL
  #   response_items_field: customers
  #   description: Shopify customer records.

  - key: products
    label: Products
    path: /products.json
    primary_key: id
    supports_incremental: true
    default_sync_mode: INCREMENTAL
    response_items_field: products
    description: Shopify product records.

  - key: shops
    label: Shops
    path: /shop.json
    primary_key: id
    supports_incremental: true
    default_sync_mode: INCREMENTAL
    response_items_field: shop
    description: Shopify shops records.
