"""initial runtime metadata schema

Revision ID: 8230e54e4fec
Revises: 
Create Date: 2026-03-27 22:55:24.125253
"""


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8230e54e4fec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ep_runtime_instances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'draining', 'offline', name='runtime_instance_status'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ep_runtime_instances_last_seen_at'), 'ep_runtime_instances', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_ep_runtime_instances_status'), 'ep_runtime_instances', ['status'], unique=False)
    op.create_index(op.f('ix_ep_runtime_instances_workspace_id'), 'ep_runtime_instances', ['workspace_id'], unique=False)
    op.create_index('ix_ep_runtime_instances_workspace_status_seen', 'ep_runtime_instances', ['workspace_id', 'status', 'last_seen_at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='job_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', name='job_priority'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lock_owner', sa.String(length=255), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status_message', sa.String(length=1024), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_lock_owner'), 'jobs', ['lock_owner'], unique=False)
    op.create_index(op.f('ix_jobs_locked_until'), 'jobs', ['locked_until'], unique=False)
    op.create_index(op.f('ix_jobs_priority'), 'jobs', ['priority'], unique=False)
    op.create_index('ix_jobs_runnable', 'jobs', ['status', 'locked_until', 'priority', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_workspace_id'), 'jobs', ['workspace_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('awaiting_user_input', 'processing', name='thread_state'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_actor_id', sa.Uuid(), nullable=False),
    sa.Column('last_message_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_created_by_actor_id'), 'threads', ['created_by_actor_id'], unique=False)
    op.create_index(op.f('ix_threads_workspace_id'), 'threads', ['workspace_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_name'), 'workspaces', ['name'], unique=True)
    op.create_table('connectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('connector_family', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('config_json', sa.String(), nullable=False),
    sa.Column('connection_metadata_json', sa.JSON(), nullable=True),
    sa.Column('secret_references_json', sa.JSON(), nullable=True),
    sa.Column('access_policy_json', sa.JSON(), nullable=True),
    sa.Column('supported_resources_json', sa.JSON(), nullable=True),
    sa.Column('sync_strategy', sa.String(length=50), nullable=True),
    sa.Column('capabilities_json', sa.JSON(), nullable=True),
    sa.Column('is_managed', sa.Boolean(), nullable=False),
    sa.Column('management_mode', sa.String(length=50), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectors_id'), 'connectors', ['id'], unique=False)
    op.create_index(op.f('ix_connectors_name'), 'connectors', ['name'], unique=True)
    op.create_index(op.f('ix_connectors_workspace_id'), 'connectors', ['workspace_id'], unique=False)
    op.create_table('conversation_memory_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('fact', 'preference', 'decision', 'tool_outcome', 'answer', name='memory_category'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_memory_items_actor_id'), 'conversation_memory_items', ['actor_id'], unique=False)
    op.create_index(op.f('ix_conversation_memory_items_category'), 'conversation_memory_items', ['category'], unique=False)
    op.create_index(op.f('ix_conversation_memory_items_created_at'), 'conversation_memory_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_memory_items_last_accessed_at'), 'conversation_memory_items', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_conversation_memory_items_thread_id'), 'conversation_memory_items', ['thread_id'], unique=False)
    op.create_table('edge_task_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('message_type', sa.String(length=128), nullable=False),
    sa.Column('message_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'leased', 'acked', 'failed', 'dead_letter', name='edge_task_status'), nullable=False),
    sa.Column('target_runtime_id', sa.Uuid(), nullable=True),
    sa.Column('lease_id', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leased_to_runtime_id', sa.Uuid(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.JSON(), nullable=True),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_runtime_id'], ['ep_runtime_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_task_records_lease_expires_at'), 'edge_task_records', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_edge_task_records_lease_id'), 'edge_task_records', ['lease_id'], unique=False)
    op.create_index(op.f('ix_edge_task_records_leased_to_runtime_id'), 'edge_task_records', ['leased_to_runtime_id'], unique=False)
    op.create_index(op.f('ix_edge_task_records_message_type'), 'edge_task_records', ['message_type'], unique=False)
    op.create_index(op.f('ix_edge_task_records_status'), 'edge_task_records', ['status'], unique=False)
    op.create_index(op.f('ix_edge_task_records_target_runtime_id'), 'edge_task_records', ['target_runtime_id'], unique=False)
    op.create_index(op.f('ix_edge_task_records_workspace_id'), 'edge_task_records', ['workspace_id'], unique=False)
    op.create_index('ix_edge_task_records_workspace_status_runtime', 'edge_task_records', ['workspace_id', 'status', 'target_runtime_id'], unique=False)
    op.create_table('ep_runtime_registration_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('runtime_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_actor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['runtime_id'], ['ep_runtime_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ep_runtime_registration_tokens_created_by_actor_id'), 'ep_runtime_registration_tokens', ['created_by_actor_id'], unique=False)
    op.create_index(op.f('ix_ep_runtime_registration_tokens_expires_at'), 'ep_runtime_registration_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_ep_runtime_registration_tokens_runtime_id'), 'ep_runtime_registration_tokens', ['runtime_id'], unique=False)
    op.create_index(op.f('ix_ep_runtime_registration_tokens_token_hash'), 'ep_runtime_registration_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_ep_runtime_registration_tokens_used_at'), 'ep_runtime_registration_tokens', ['used_at'], unique=False)
    op.create_index(op.f('ix_ep_runtime_registration_tokens_workspace_id'), 'ep_runtime_registration_tokens', ['workspace_id'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'internal', name='job_event_visibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('job_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_tasks_job_id'), 'job_tasks', ['job_id'], unique=False)
    op.create_table('lineage_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('edge_type', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'source_type', 'source_id', 'target_type', 'target_id', 'edge_type', name='uq_lineage_edges_workspace_source_target_edge')
    )
    op.create_index('ix_lineage_edges_workspace_created_at', 'lineage_edges', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_lineage_edges_workspace_id'), 'lineage_edges', ['workspace_id'], unique=False)
    op.create_index('ix_lineage_edges_workspace_source', 'lineage_edges', ['workspace_id', 'source_type', 'source_id'], unique=False)
    op.create_index('ix_lineage_edges_workspace_target', 'lineage_edges', ['workspace_id', 'target_type', 'target_id'], unique=False)
    op.create_table('llm_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_connections_workspace_id'), 'llm_connections', ['workspace_id'], unique=False)
    op.create_table('runtime_actors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('actor_type', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('roles_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'subject', name='uq_runtime_actors_workspace_subject')
    )
    op.create_index(op.f('ix_runtime_actors_email'), 'runtime_actors', ['email'], unique=False)
    op.create_index(op.f('ix_runtime_actors_subject'), 'runtime_actors', ['subject'], unique=False)
    op.create_index(op.f('ix_runtime_actors_workspace_id'), 'runtime_actors', ['workspace_id'], unique=False)
    op.create_table('runtime_local_auth_state',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('session_secret', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('thread_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('parent_message_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('system', 'user', 'assistant', 'tool', name='message_role'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('model_snapshot', sa.JSON(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_messages_thread_id'), 'thread_messages', ['thread_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('llm_connection_id', sa.Uuid(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('management_mode', sa.String(length=50), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['llm_connection_id'], ['llm_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_connectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['connectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connector_sync_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('connector_type', sa.String(length=64), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('sync_mode', sa.String(length=32), nullable=False),
    sa.Column('last_cursor', sa.String(length=255), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('dataset_ids_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('records_synced', sa.BigInteger(), nullable=False),
    sa.Column('bytes_synced', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connectors.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'connection_id', 'resource_name', name='uq_connector_sync_states_workspace_connection_resource')
    )
    op.create_index(op.f('ix_connector_sync_states_connection_id'), 'connector_sync_states', ['connection_id'], unique=False)
    op.create_index(op.f('ix_connector_sync_states_updated_at'), 'connector_sync_states', ['updated_at'], unique=False)
    op.create_index('ix_connector_sync_states_workspace_connection_updated', 'connector_sync_states', ['workspace_id', 'connection_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_connector_sync_states_workspace_id'), 'connector_sync_states', ['workspace_id'], unique=False)
    op.create_index('ix_connector_sync_states_workspace_resource', 'connector_sync_states', ['workspace_id', 'resource_name'], unique=False)
    op.create_table('database_connectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['connectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_actor_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_actor_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sql_alias', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('dataset_type', sa.String(length=32), nullable=False),
    sa.Column('materialization_mode', sa.String(length=32), nullable=True),
    sa.Column('source_kind', sa.String(length=32), nullable=True),
    sa.Column('connector_kind', sa.String(length=64), nullable=True),
    sa.Column('storage_kind', sa.String(length=32), nullable=True),
    sa.Column('dialect', sa.String(length=64), nullable=True),
    sa.Column('catalog_name', sa.String(length=255), nullable=True),
    sa.Column('schema_name', sa.String(length=255), nullable=True),
    sa.Column('table_name', sa.String(length=255), nullable=True),
    sa.Column('storage_uri', sa.String(length=2048), nullable=True),
    sa.Column('sql_text', sa.Text(), nullable=True),
    sa.Column('relation_identity_json', sa.JSON(), nullable=True),
    sa.Column('execution_capabilities_json', sa.JSON(), nullable=True),
    sa.Column('referenced_dataset_ids_json', sa.JSON(), nullable=False),
    sa.Column('federated_plan_json', sa.JSON(), nullable=True),
    sa.Column('file_config_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('revision_id', sa.Uuid(), nullable=True),
    sa.Column('row_count_estimate', sa.BigInteger(), nullable=True),
    sa.Column('bytes_estimate', sa.BigInteger(), nullable=True),
    sa.Column('last_profiled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('management_mode', sa.String(length=50), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_datasets_workspace_name'),
    sa.UniqueConstraint('workspace_id', 'sql_alias', name='uq_datasets_workspace_sql_alias')
    )
    op.create_index(op.f('ix_datasets_connection_id'), 'datasets', ['connection_id'], unique=False)
    op.create_index(op.f('ix_datasets_connector_kind'), 'datasets', ['connector_kind'], unique=False)
    op.create_index(op.f('ix_datasets_created_by_actor_id'), 'datasets', ['created_by_actor_id'], unique=False)
    op.create_index(op.f('ix_datasets_dataset_type'), 'datasets', ['dataset_type'], unique=False)
    op.create_index(op.f('ix_datasets_materialization_mode'), 'datasets', ['materialization_mode'], unique=False)
    op.create_index(op.f('ix_datasets_source_kind'), 'datasets', ['source_kind'], unique=False)
    op.create_index(op.f('ix_datasets_storage_kind'), 'datasets', ['storage_kind'], unique=False)
    op.create_index(op.f('ix_datasets_updated_at'), 'datasets', ['updated_at'], unique=False)
    op.create_index(op.f('ix_datasets_updated_by_actor_id'), 'datasets', ['updated_by_actor_id'], unique=False)
    op.create_index(op.f('ix_datasets_workspace_id'), 'datasets', ['workspace_id'], unique=False)
    op.create_index('ix_datasets_workspace_name', 'datasets', ['workspace_id', 'name'], unique=False)
    op.create_index('ix_datasets_workspace_sql_alias', 'datasets', ['workspace_id', 'sql_alias'], unique=False)
    op.create_index('ix_datasets_workspace_updated_at', 'datasets', ['workspace_id', 'updated_at'], unique=False)
    op.create_table('edge_result_receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('runtime_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('payload_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['edge_task_records.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'runtime_id', 'request_id', name='uq_edge_result_receipt_workspace_request')
    )
    op.create_index(op.f('ix_edge_result_receipts_runtime_id'), 'edge_result_receipts', ['runtime_id'], unique=False)
    op.create_index(op.f('ix_edge_result_receipts_task_id'), 'edge_result_receipts', ['task_id'], unique=False)
    op.create_index(op.f('ix_edge_result_receipts_workspace_id'), 'edge_result_receipts', ['workspace_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('root_message_id', sa.Uuid(), nullable=False),
    sa.Column('graph', sa.JSON(), nullable=True),
    sa.Column('state_before', sa.JSON(), nullable=True),
    sa.Column('state_after', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', 'cancelled', name='run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['root_message_id'], ['thread_messages.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_job_id'), 'runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_runs_thread_id'), 'runs', ['thread_id'], unique=False)
    op.create_table('runtime_local_auth_credentials',
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['runtime_actors.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('actor_id')
    )
    op.create_index(op.f('ix_runtime_local_auth_credentials_workspace_id'), 'runtime_local_auth_credentials', ['workspace_id'], unique=False)
    op.create_table('semantic_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('content_yaml', sa.Text(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('management_mode', sa.String(length=50), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_models_workspace_id'), 'semantic_models', ['workspace_id'], unique=False)
    op.create_table('sql_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=True),
    sa.Column('workbench_mode', sa.String(length=32), nullable=False),
    sa.Column('selected_datasets_json', sa.JSON(), nullable=False),
    sa.Column('execution_mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_hash', sa.String(length=128), nullable=False),
    sa.Column('query_params_json', sa.JSON(), nullable=False),
    sa.Column('requested_limit', sa.Integer(), nullable=True),
    sa.Column('enforced_limit', sa.Integer(), nullable=False),
    sa.Column('requested_timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('enforced_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('is_explain', sa.Boolean(), nullable=False),
    sa.Column('is_federated', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('policy_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('result_columns_json', sa.JSON(), nullable=True),
    sa.Column('result_rows_json', sa.JSON(), nullable=True),
    sa.Column('row_count_preview', sa.Integer(), nullable=False),
    sa.Column('total_rows_estimate', sa.Integer(), nullable=True),
    sa.Column('bytes_scanned', sa.BigInteger(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('result_cursor', sa.String(length=255), nullable=True),
    sa.Column('redaction_applied', sa.Boolean(), nullable=False),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('warning_json', sa.JSON(), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sql_job_actor_id'), 'sql_job', ['actor_id'], unique=False)
    op.create_index(op.f('ix_sql_job_connection_id'), 'sql_job', ['connection_id'], unique=False)
    op.create_index(op.f('ix_sql_job_correlation_id'), 'sql_job', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_sql_job_created_at'), 'sql_job', ['created_at'], unique=False)
    op.create_index(op.f('ix_sql_job_query_hash'), 'sql_job', ['query_hash'], unique=False)
    op.create_index(op.f('ix_sql_job_status'), 'sql_job', ['status'], unique=False)
    op.create_index(op.f('ix_sql_job_workbench_mode'), 'sql_job', ['workbench_mode'], unique=False)
    op.create_index('ix_sql_job_workspace_created_at', 'sql_job', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sql_job_workspace_id'), 'sql_job', ['workspace_id'], unique=False)
    op.create_index('ix_sql_job_workspace_status_created_at', 'sql_job', ['workspace_id', 'status', 'created_at'], unique=False)
    op.create_table('sql_workspace_policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('max_preview_rows', sa.Integer(), nullable=False),
    sa.Column('max_export_rows', sa.Integer(), nullable=False),
    sa.Column('max_runtime_seconds', sa.Integer(), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('allow_dml', sa.Boolean(), nullable=False),
    sa.Column('allow_federation', sa.Boolean(), nullable=False),
    sa.Column('allowed_schemas_json', sa.JSON(), nullable=False),
    sa.Column('allowed_tables_json', sa.JSON(), nullable=False),
    sa.Column('default_datasource_id', sa.Uuid(), nullable=True),
    sa.Column('budget_limit_bytes', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_actor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_datasource_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sql_workspace_policy_created_at'), 'sql_workspace_policy', ['created_at'], unique=False)
    op.create_index(op.f('ix_sql_workspace_policy_updated_by_actor_id'), 'sql_workspace_policy', ['updated_by_actor_id'], unique=False)
    op.create_index(op.f('ix_sql_workspace_policy_workspace_id'), 'sql_workspace_policy', ['workspace_id'], unique=True)
    op.create_table('tool_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['thread_messages.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_message_id'), 'tool_calls', ['message_id'], unique=False)
    op.create_table('dataset_columns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=128), nullable=False),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('ordinal_position', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('is_computed', sa.Boolean(), nullable=False),
    sa.Column('expression', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'name', name='uq_dataset_columns_dataset_name')
    )
    op.create_index(op.f('ix_dataset_columns_dataset_id'), 'dataset_columns', ['dataset_id'], unique=False)
    op.create_index('ix_dataset_columns_dataset_ordinal', 'dataset_columns', ['dataset_id', 'ordinal_position'], unique=False)
    op.create_index(op.f('ix_dataset_columns_workspace_id'), 'dataset_columns', ['workspace_id'], unique=False)
    op.create_table('dataset_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('max_rows_preview', sa.Integer(), nullable=False),
    sa.Column('max_export_rows', sa.Integer(), nullable=False),
    sa.Column('redaction_rules_json', sa.JSON(), nullable=False),
    sa.Column('row_filters_json', sa.JSON(), nullable=False),
    sa.Column('allow_dml', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_policies_dataset_id'), 'dataset_policies', ['dataset_id'], unique=True)
    op.create_index(op.f('ix_dataset_policies_workspace_id'), 'dataset_policies', ['workspace_id'], unique=False)
    op.create_table('dataset_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('revision_hash', sa.String(length=64), nullable=True),
    sa.Column('change_summary', sa.String(length=1024), nullable=True),
    sa.Column('definition_json', sa.JSON(), nullable=True),
    sa.Column('schema_json', sa.JSON(), nullable=True),
    sa.Column('policy_json', sa.JSON(), nullable=True),
    sa.Column('source_bindings_json', sa.JSON(), nullable=True),
    sa.Column('execution_characteristics_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('created_by_actor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'revision_number', name='uq_dataset_revisions_number')
    )
    op.create_index(op.f('ix_dataset_revisions_created_by_actor_id'), 'dataset_revisions', ['created_by_actor_id'], unique=False)
    op.create_index('ix_dataset_revisions_dataset_created_at', 'dataset_revisions', ['dataset_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_dataset_revisions_dataset_id'), 'dataset_revisions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_revisions_revision_hash'), 'dataset_revisions', ['revision_hash'], unique=False)
    op.create_index('ix_dataset_revisions_workspace_created_at', 'dataset_revisions', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_dataset_revisions_workspace_id'), 'dataset_revisions', ['workspace_id'], unique=False)
    op.create_table('semantic_vector_indexes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('semantic_model_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_key', sa.String(length=255), nullable=False),
    sa.Column('dimension_name', sa.String(length=255), nullable=False),
    sa.Column('vector_store_target', sa.String(length=64), nullable=False),
    sa.Column('vector_connector_name', sa.String(length=255), nullable=True),
    sa.Column('vector_connector_id', sa.Uuid(), nullable=True),
    sa.Column('vector_index_name', sa.String(length=255), nullable=False),
    sa.Column('refresh_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('refresh_status', sa.String(length=32), nullable=False),
    sa.Column('indexed_value_count', sa.Integer(), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('last_refresh_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refresh_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_models.id'], ),
    sa.ForeignKeyConstraint(['vector_connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'semantic_model_id', 'dataset_key', 'dimension_name', name='uq_semantic_vector_index_dimension')
    )
    op.create_index(op.f('ix_semantic_vector_indexes_semantic_model_id'), 'semantic_vector_indexes', ['semantic_model_id'], unique=False)
    op.create_index(op.f('ix_semantic_vector_indexes_workspace_id'), 'semantic_vector_indexes', ['workspace_id'], unique=False)
    op.create_table('sql_job_result_artifact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sql_job_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_actor_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_backend', sa.String(length=32), nullable=False),
    sa.Column('storage_reference', sa.String(length=1024), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sql_job_id'], ['sql_job.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sql_job_result_artifact_created_at'), 'sql_job_result_artifact', ['created_at'], unique=False)
    op.create_index(op.f('ix_sql_job_result_artifact_created_by_actor_id'), 'sql_job_result_artifact', ['created_by_actor_id'], unique=False)
    op.create_index(op.f('ix_sql_job_result_artifact_sql_job_id'), 'sql_job_result_artifact', ['sql_job_id'], unique=False)
    op.create_index('ix_sql_job_result_artifact_workspace_created_at', 'sql_job_result_artifact', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sql_job_result_artifact_workspace_id'), 'sql_job_result_artifact', ['workspace_id'], unique=False)
    op.create_table('sql_saved_query',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_actor_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_actor_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=True),
    sa.Column('workbench_mode', sa.String(length=32), nullable=False),
    sa.Column('selected_datasets_json', sa.JSON(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_hash', sa.String(length=128), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('default_params_json', sa.JSON(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('last_sql_job_id', sa.Uuid(), nullable=True),
    sa.Column('last_result_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['last_result_artifact_id'], ['sql_job_result_artifact.id'], ),
    sa.ForeignKeyConstraint(['last_sql_job_id'], ['sql_job.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sql_saved_query_connection_id'), 'sql_saved_query', ['connection_id'], unique=False)
    op.create_index(op.f('ix_sql_saved_query_created_at'), 'sql_saved_query', ['created_at'], unique=False)
    op.create_index(op.f('ix_sql_saved_query_created_by_actor_id'), 'sql_saved_query', ['created_by_actor_id'], unique=False)
    op.create_index(op.f('ix_sql_saved_query_is_shared'), 'sql_saved_query', ['is_shared'], unique=False)
    op.create_index(op.f('ix_sql_saved_query_query_hash'), 'sql_saved_query', ['query_hash'], unique=False)
    op.create_index(op.f('ix_sql_saved_query_updated_by_actor_id'), 'sql_saved_query', ['updated_by_actor_id'], unique=False)
    op.create_index(op.f('ix_sql_saved_query_workbench_mode'), 'sql_saved_query', ['workbench_mode'], unique=False)
    op.create_index('ix_sql_saved_query_workspace_created_at', 'sql_saved_query', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sql_saved_query_workspace_id'), 'sql_saved_query', ['workspace_id'], unique=False)
    op.create_index('ix_sql_saved_query_workspace_updated_at', 'sql_saved_query', ['workspace_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sql_saved_query_workspace_updated_at', table_name='sql_saved_query')
    op.drop_index(op.f('ix_sql_saved_query_workspace_id'), table_name='sql_saved_query')
    op.drop_index('ix_sql_saved_query_workspace_created_at', table_name='sql_saved_query')
    op.drop_index(op.f('ix_sql_saved_query_workbench_mode'), table_name='sql_saved_query')
    op.drop_index(op.f('ix_sql_saved_query_updated_by_actor_id'), table_name='sql_saved_query')
    op.drop_index(op.f('ix_sql_saved_query_query_hash'), table_name='sql_saved_query')
    op.drop_index(op.f('ix_sql_saved_query_is_shared'), table_name='sql_saved_query')
    op.drop_index(op.f('ix_sql_saved_query_created_by_actor_id'), table_name='sql_saved_query')
    op.drop_index(op.f('ix_sql_saved_query_created_at'), table_name='sql_saved_query')
    op.drop_index(op.f('ix_sql_saved_query_connection_id'), table_name='sql_saved_query')
    op.drop_table('sql_saved_query')
    op.drop_index(op.f('ix_sql_job_result_artifact_workspace_id'), table_name='sql_job_result_artifact')
    op.drop_index('ix_sql_job_result_artifact_workspace_created_at', table_name='sql_job_result_artifact')
    op.drop_index(op.f('ix_sql_job_result_artifact_sql_job_id'), table_name='sql_job_result_artifact')
    op.drop_index(op.f('ix_sql_job_result_artifact_created_by_actor_id'), table_name='sql_job_result_artifact')
    op.drop_index(op.f('ix_sql_job_result_artifact_created_at'), table_name='sql_job_result_artifact')
    op.drop_table('sql_job_result_artifact')
    op.drop_index(op.f('ix_semantic_vector_indexes_workspace_id'), table_name='semantic_vector_indexes')
    op.drop_index(op.f('ix_semantic_vector_indexes_semantic_model_id'), table_name='semantic_vector_indexes')
    op.drop_table('semantic_vector_indexes')
    op.drop_index(op.f('ix_dataset_revisions_workspace_id'), table_name='dataset_revisions')
    op.drop_index('ix_dataset_revisions_workspace_created_at', table_name='dataset_revisions')
    op.drop_index(op.f('ix_dataset_revisions_revision_hash'), table_name='dataset_revisions')
    op.drop_index(op.f('ix_dataset_revisions_dataset_id'), table_name='dataset_revisions')
    op.drop_index('ix_dataset_revisions_dataset_created_at', table_name='dataset_revisions')
    op.drop_index(op.f('ix_dataset_revisions_created_by_actor_id'), table_name='dataset_revisions')
    op.drop_table('dataset_revisions')
    op.drop_index(op.f('ix_dataset_policies_workspace_id'), table_name='dataset_policies')
    op.drop_index(op.f('ix_dataset_policies_dataset_id'), table_name='dataset_policies')
    op.drop_table('dataset_policies')
    op.drop_index(op.f('ix_dataset_columns_workspace_id'), table_name='dataset_columns')
    op.drop_index('ix_dataset_columns_dataset_ordinal', table_name='dataset_columns')
    op.drop_index(op.f('ix_dataset_columns_dataset_id'), table_name='dataset_columns')
    op.drop_table('dataset_columns')
    op.drop_index(op.f('ix_tool_calls_message_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_sql_workspace_policy_workspace_id'), table_name='sql_workspace_policy')
    op.drop_index(op.f('ix_sql_workspace_policy_updated_by_actor_id'), table_name='sql_workspace_policy')
    op.drop_index(op.f('ix_sql_workspace_policy_created_at'), table_name='sql_workspace_policy')
    op.drop_table('sql_workspace_policy')
    op.drop_index('ix_sql_job_workspace_status_created_at', table_name='sql_job')
    op.drop_index(op.f('ix_sql_job_workspace_id'), table_name='sql_job')
    op.drop_index('ix_sql_job_workspace_created_at', table_name='sql_job')
    op.drop_index(op.f('ix_sql_job_workbench_mode'), table_name='sql_job')
    op.drop_index(op.f('ix_sql_job_status'), table_name='sql_job')
    op.drop_index(op.f('ix_sql_job_query_hash'), table_name='sql_job')
    op.drop_index(op.f('ix_sql_job_created_at'), table_name='sql_job')
    op.drop_index(op.f('ix_sql_job_correlation_id'), table_name='sql_job')
    op.drop_index(op.f('ix_sql_job_connection_id'), table_name='sql_job')
    op.drop_index(op.f('ix_sql_job_actor_id'), table_name='sql_job')
    op.drop_table('sql_job')
    op.drop_index(op.f('ix_semantic_models_workspace_id'), table_name='semantic_models')
    op.drop_table('semantic_models')
    op.drop_index(op.f('ix_runtime_local_auth_credentials_workspace_id'), table_name='runtime_local_auth_credentials')
    op.drop_table('runtime_local_auth_credentials')
    op.drop_index(op.f('ix_runs_thread_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_job_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_edge_result_receipts_workspace_id'), table_name='edge_result_receipts')
    op.drop_index(op.f('ix_edge_result_receipts_task_id'), table_name='edge_result_receipts')
    op.drop_index(op.f('ix_edge_result_receipts_runtime_id'), table_name='edge_result_receipts')
    op.drop_table('edge_result_receipts')
    op.drop_index('ix_datasets_workspace_updated_at', table_name='datasets')
    op.drop_index('ix_datasets_workspace_sql_alias', table_name='datasets')
    op.drop_index('ix_datasets_workspace_name', table_name='datasets')
    op.drop_index(op.f('ix_datasets_workspace_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_updated_by_actor_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_updated_at'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_storage_kind'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_source_kind'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_materialization_mode'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_dataset_type'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_created_by_actor_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_connector_kind'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_connection_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_table('database_connectors')
    op.drop_index('ix_connector_sync_states_workspace_resource', table_name='connector_sync_states')
    op.drop_index(op.f('ix_connector_sync_states_workspace_id'), table_name='connector_sync_states')
    op.drop_index('ix_connector_sync_states_workspace_connection_updated', table_name='connector_sync_states')
    op.drop_index(op.f('ix_connector_sync_states_updated_at'), table_name='connector_sync_states')
    op.drop_index(op.f('ix_connector_sync_states_connection_id'), table_name='connector_sync_states')
    op.drop_table('connector_sync_states')
    op.drop_table('api_connectors')
    op.drop_table('agents')
    op.drop_index(op.f('ix_thread_messages_thread_id'), table_name='thread_messages')
    op.drop_table('thread_messages')
    op.drop_table('runtime_local_auth_state')
    op.drop_index(op.f('ix_runtime_actors_workspace_id'), table_name='runtime_actors')
    op.drop_index(op.f('ix_runtime_actors_subject'), table_name='runtime_actors')
    op.drop_index(op.f('ix_runtime_actors_email'), table_name='runtime_actors')
    op.drop_table('runtime_actors')
    op.drop_index(op.f('ix_llm_connections_workspace_id'), table_name='llm_connections')
    op.drop_table('llm_connections')
    op.drop_index('ix_lineage_edges_workspace_target', table_name='lineage_edges')
    op.drop_index('ix_lineage_edges_workspace_source', table_name='lineage_edges')
    op.drop_index(op.f('ix_lineage_edges_workspace_id'), table_name='lineage_edges')
    op.drop_index('ix_lineage_edges_workspace_created_at', table_name='lineage_edges')
    op.drop_table('lineage_edges')
    op.drop_index(op.f('ix_job_tasks_job_id'), table_name='job_tasks')
    op.drop_table('job_tasks')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_ep_runtime_registration_tokens_workspace_id'), table_name='ep_runtime_registration_tokens')
    op.drop_index(op.f('ix_ep_runtime_registration_tokens_used_at'), table_name='ep_runtime_registration_tokens')
    op.drop_index(op.f('ix_ep_runtime_registration_tokens_token_hash'), table_name='ep_runtime_registration_tokens')
    op.drop_index(op.f('ix_ep_runtime_registration_tokens_runtime_id'), table_name='ep_runtime_registration_tokens')
    op.drop_index(op.f('ix_ep_runtime_registration_tokens_expires_at'), table_name='ep_runtime_registration_tokens')
    op.drop_index(op.f('ix_ep_runtime_registration_tokens_created_by_actor_id'), table_name='ep_runtime_registration_tokens')
    op.drop_table('ep_runtime_registration_tokens')
    op.drop_index('ix_edge_task_records_workspace_status_runtime', table_name='edge_task_records')
    op.drop_index(op.f('ix_edge_task_records_workspace_id'), table_name='edge_task_records')
    op.drop_index(op.f('ix_edge_task_records_target_runtime_id'), table_name='edge_task_records')
    op.drop_index(op.f('ix_edge_task_records_status'), table_name='edge_task_records')
    op.drop_index(op.f('ix_edge_task_records_message_type'), table_name='edge_task_records')
    op.drop_index(op.f('ix_edge_task_records_leased_to_runtime_id'), table_name='edge_task_records')
    op.drop_index(op.f('ix_edge_task_records_lease_id'), table_name='edge_task_records')
    op.drop_index(op.f('ix_edge_task_records_lease_expires_at'), table_name='edge_task_records')
    op.drop_table('edge_task_records')
    op.drop_index(op.f('ix_conversation_memory_items_thread_id'), table_name='conversation_memory_items')
    op.drop_index(op.f('ix_conversation_memory_items_last_accessed_at'), table_name='conversation_memory_items')
    op.drop_index(op.f('ix_conversation_memory_items_created_at'), table_name='conversation_memory_items')
    op.drop_index(op.f('ix_conversation_memory_items_category'), table_name='conversation_memory_items')
    op.drop_index(op.f('ix_conversation_memory_items_actor_id'), table_name='conversation_memory_items')
    op.drop_table('conversation_memory_items')
    op.drop_index(op.f('ix_connectors_workspace_id'), table_name='connectors')
    op.drop_index(op.f('ix_connectors_name'), table_name='connectors')
    op.drop_index(op.f('ix_connectors_id'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_index(op.f('ix_workspaces_name'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_threads_workspace_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_created_by_actor_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_jobs_workspace_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index('ix_jobs_runnable', table_name='jobs')
    op.drop_index(op.f('ix_jobs_priority'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_locked_until'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_lock_owner'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_ep_runtime_instances_workspace_status_seen', table_name='ep_runtime_instances')
    op.drop_index(op.f('ix_ep_runtime_instances_workspace_id'), table_name='ep_runtime_instances')
    op.drop_index(op.f('ix_ep_runtime_instances_status'), table_name='ep_runtime_instances')
    op.drop_index(op.f('ix_ep_runtime_instances_last_seen_at'), table_name='ep_runtime_instances')
    op.drop_table('ep_runtime_instances')
    # ### end Alembic commands ###
