"""Core plugin interfaces for the Langbridge runtime monolith.

Official connector implementations stay in the separate ``langbridge-connectors``
package and register themselves through this core surface.
"""

from langbridge.packages.connectors.langbridge_connectors.api.config import (
    BaseConnectorConfig,
    BaseConnectorConfigFactory,
    BaseConnectorConfigSchemaFactory,
    ConnectorAuthFieldSchema,
    ConnectorConfigEntrySchema,
    ConnectorConfigSchema,
    ConnectorFamily,
    ConnectorPluginMetadata,
    ConnectorRuntimeType,
    ConnectorSyncStrategy,
    get_connector_config_factory,
    get_connector_config_schema_factory,
)
from langbridge.packages.connectors.langbridge_connectors.api.connector import (
    ApiConnector,
    ApiExtractResult,
    ApiResource,
    ApiSyncResult,
    AuthError,
    Connector,
    ConnectorError,
    ConnectorRuntimeTypeSqlDialectMap,
    ConnectorRuntimeTypeVectorDBMap,
    ConnectorType,
    ManagedVectorDB,
    QueryResult,
    SqlConnector,
    SqlDialetcs,
    VecotorDBConnector,
    VectorDBType,
    VectorType,
    run_sync,
)
from langbridge.packages.connectors.langbridge_connectors.api.registry import (
    ApiConnectorFactory,
    ConnectorInstanceRegistry,
    ConnectorPlugin,
    ConnectorPluginRegistry,
    SqlConnectorFactory,
    VectorDBConnectorFactory,
    ensure_builtin_plugins_loaded,
    get_connector_plugin,
    list_connector_plugins,
    register_connector_plugin,
)

__all__ = [
    "ApiConnector",
    "ApiConnectorFactory",
    "ApiExtractResult",
    "ApiResource",
    "ApiSyncResult",
    "AuthError",
    "BaseConnectorConfig",
    "BaseConnectorConfigFactory",
    "BaseConnectorConfigSchemaFactory",
    "Connector",
    "ConnectorAuthFieldSchema",
    "ConnectorConfigEntrySchema",
    "ConnectorConfigSchema",
    "ConnectorError",
    "ConnectorFamily",
    "ConnectorInstanceRegistry",
    "ConnectorPlugin",
    "ConnectorPluginMetadata",
    "ConnectorPluginRegistry",
    "ConnectorRuntimeType",
    "ConnectorRuntimeTypeSqlDialectMap",
    "ConnectorRuntimeTypeVectorDBMap",
    "ConnectorSyncStrategy",
    "ConnectorType",
    "ManagedVectorDB",
    "QueryResult",
    "SqlConnector",
    "SqlConnectorFactory",
    "SqlDialetcs",
    "VecotorDBConnector",
    "VectorDBConnectorFactory",
    "VectorDBType",
    "VectorType",
    "ensure_builtin_plugins_loaded",
    "get_connector_config_factory",
    "get_connector_config_schema_factory",
    "get_connector_plugin",
    "list_connector_plugins",
    "register_connector_plugin",
    "run_sync",
]
