from types import SimpleNamespace
import uuid

import pytest

from langbridge.apps.api.langbridge_api.services.semantic.semantic_model_service import (
    SemanticModelService,
)
from langbridge.packages.common.langbridge_common.contracts.semantic import (
    SemanticModelCatalogColumnResponse,
    SemanticModelCatalogResponse,
    SemanticModelCatalogSchemaResponse,
    SemanticModelCatalogTableResponse,
)


@pytest.fixture
def anyio_backend():
    return "asyncio"


def _build_service() -> SemanticModelService:
    return SemanticModelService(
        repository=SimpleNamespace(),
        builder=SimpleNamespace(),
        organization_repository=SimpleNamespace(),
        project_repository=SimpleNamespace(),
        connector_service=SimpleNamespace(),
        agent_service=SimpleNamespace(),
        semantic_search_service=SimpleNamespace(),
        emvironment_service=SimpleNamespace(),
    )


def _build_catalog(connector_id: uuid.UUID) -> SemanticModelCatalogResponse:
    return SemanticModelCatalogResponse(
        connector_id=connector_id,
        schemas=[
            SemanticModelCatalogSchemaResponse(
                name="sales",
                tables=[
                    SemanticModelCatalogTableResponse(
                        schema="sales",
                        name="orders",
                        fully_qualified_name="sales.orders",
                        columns=[
                            SemanticModelCatalogColumnResponse(name="order_id", type="integer", primary_key=True),
                            SemanticModelCatalogColumnResponse(name="customer_id", type="integer", primary_key=False),
                            SemanticModelCatalogColumnResponse(name="amount", type="decimal", primary_key=False),
                        ],
                    ),
                    SemanticModelCatalogTableResponse(
                        schema="sales",
                        name="customers",
                        fully_qualified_name="sales.customers",
                        columns=[
                            SemanticModelCatalogColumnResponse(name="customer_id", type="integer", primary_key=True),
                            SemanticModelCatalogColumnResponse(name="region", type="string", primary_key=False),
                        ],
                    ),
                ],
            )
        ],
        table_count=2,
        column_count=5,
    )


@pytest.mark.anyio
async def test_generate_model_yaml_from_selection_returns_yaml_with_selected_columns(monkeypatch) -> None:
    connector_id = uuid.uuid4()
    service = _build_service()
    catalog = _build_catalog(connector_id)
    foreign_keys = [
        SimpleNamespace(schema="sales", table="customers", column="customer_id", foreign_key="customer_id")
    ]
    sql_connector = SimpleNamespace(
        fetch_foreign_keys=lambda _schema, table: foreign_keys if table == "orders" else [],
    )

    async def _load_sql_connector(_connector_id):
        return SimpleNamespace(name="sales-db"), sql_connector

    async def _get_foreign_keys(schema, table):
        if table == "orders":
            return foreign_keys
        return []

    sql_connector.fetch_foreign_keys = _get_foreign_keys

    async def _get_catalog(_connector_id):
        return catalog

    monkeypatch.setattr(service, "_load_sql_connector", _load_sql_connector)
    monkeypatch.setattr(service, "get_connector_catalog", _get_catalog)

    response = await service.generate_model_yaml_from_selection(
        connector_id=connector_id,
        selected_tables=["sales.orders", "sales.customers"],
        selected_columns={
            "sales.orders": ["order_id", "customer_id", "amount"],
            "sales.customers": ["customer_id", "region"],
        },
        include_sample_values=False,
        description="Generated by test",
    )

    assert "sales_orders" in response.yaml_text
    assert "sales_customers" in response.yaml_text
    assert "relationships:" in response.yaml_text
    assert isinstance(response.warnings, list)
